# Generated by Django 4.2.11 on 2024-05-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_identity_experience_identites'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='first_gen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='international_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
