# Generated by Django 4.2.11 on 2024-05-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_experience_phd_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='identites',
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
