# Generated by Django 4.2.11 on 2024-05-30 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_experience_identites_delete_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('phd_year', models.IntegerField(blank=True, null=True)),
                ('international_student', models.BooleanField(blank=True, null=True)),
                ('first_gen', models.BooleanField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
