# Generated by Django 4.2.11 on 2024-05-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_note_delete_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reference',
            field=models.ManyToManyField(to='core.note'),
        ),
    ]
