# Generated by Django 4.2.11 on 2024-05-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='reference',
        ),
        migrations.AddField(
            model_name='note',
            name='is_seed_note',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='seed_note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.note'),
            preserve_default=False,
        ),
    ]
