# Generated by Django 4.2.11 on 2024-05-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_note_reference_note_is_seed_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='seed_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.note'),
        ),
    ]
