# Generated by Django 4.2.11 on 2024-06-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_note_created_at_tag_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='branch_notes',
            field=models.ManyToManyField(blank=True, null=True, to='core.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='seed_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.note'),
        ),
    ]
