# Generated by Django 4.2.11 on 2024-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_note_branch_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_seed_note',
        ),
        migrations.AddField(
            model_name='note',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
