# Generated by Django 4.2.11 on 2024-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_note_is_seed_note_note_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='phd_year',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
