# Generated by Django 4.2.11 on 2024-06-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_note_phd_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='experience_tags',
        ),
    ]
