# Generated by Django 4.2.11 on 2024-06-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_tags_note_experience_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='choice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
