# Generated by Django 4.2.11 on 2024-06-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_experience_tags_customuser_experiences'),
        ('core', '0021_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='experience_tags',
            new_name='experiences',
        ),
    ]
