# Generated by Django 4.2.11 on 2024-06-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_tag_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topics',
            field=models.ManyToManyField(to='core.topic'),
        ),
    ]
