# Generated by Django 4.2.11 on 2024-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_note_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='username_pseudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
