# Generated by Django 4.2.11 on 2024-05-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phd_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
