# Generated by Django 4.2.11 on 2024-05-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phd_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_gen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='international_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
