# Generated by Django 4.2.11 on 2024-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_first_gen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phd_year_boundary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
