# Generated by Django 4.2.11 on 2024-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_tags_note_experience_tags'),
        ('accounts', '0005_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
